### ISSUE TITLE
Espinita not working when used in multiple models.

### ISSUE THREAD

**Issue by ravindrakanak017** [continuum/espinita#17]
I have tested espinita with mu user table and it works properly, but when i used it in another model it through while restarting the server "undefined local variable or method 'auditable' for class" . What could be the problem in using auditing for multiple models same time.

**Comment by ravindrakanak017** [comment]
Issue is fixed some how but i am still amazed with the strange behavior. In some places i have to use 
"include Espinita::AuditorBehavior " above auditable and on some places it works without it.

**Comment by michelson** [comment]
can't reproduce this, would be great if you can give an example or a test case , for the meanwhile I'm going to close this issue

**Comment by ravindrakanak017** [comment]
I have resolved the issue myself now it's working properly on my end. Thanks
