### ISSUE TITLE
Restoring from audits

### ISSUE THREAD

**Issue by rossettistone** [continuum/espinita#19]
Thanks very much for providing this gem! Has proven very useful.

I've had a few occasions where espinita audits served as a way to roll records back to previous states, e.g. for (minor) disaster recovery. I've put together some ad hoc scripts for this, but it seems like this might be useful core functionality for the gem.

Would you be amenable to a PR with the following approximate features?
-Restore to a point in history
`Post.find(12345).restore_from_audits(property: 'title', date: '2005/12/24')`

-View a concise history of an individual property. The full audits log is often a bit too verbose for quick readability at the command line.
`Post.find(12345).history_from_audits_for('title')`
`=> [["Foo", "2014/4/1"], ["Bar", "2014/4/7"], ["Baz", "2014/4/19"]]`

The code above is not a proposal for the exact public API syntax - just giving examples of some use cases that I'd like to solve for.

If you think others would use this functionality and you're willing to review a PR, I'm willing to put in the time to make one :-)

**Comment by michelson** [comment]
Amazing! please be my guest. it's a very useful feature, I'm totally agree!

Best!

**Comment by rossettistone** [comment]
https://github.com/continuum/espinita/pull/20
